### ISSUE TITLE
Possible to change the font size?

### ISSUE THREAD

**Issue by nikolac** [carlosefr/pcd8544#3]
I'd like to cram more info into my tiny screen, if possible.

**Comment by carlosefr** [comment]
The hardware's line height is 8 pixels tall, which is what this library uses for the font size. To use a smaller font, besides creating the font, you'd need to store the contents of the screen in memory to be able to do partial updates. This library doesn't do this, as it's main purpose is a small memory footprint. 

I suggest looking into Adafruit's library, if using a smaller font is really important to you.

**Comment by nikolac** [comment]
Ah, I understand now. Thank you for the info!
