### ISSUE TITLE
just a question : where is defined lcd.print()

### ISSUE THREAD

**Issue by philippedc** [carlosefr/pcd8544#6]
Hi Carlos, many thanks for sharing this library, it is amazing for my small low power Atmega328p projects :)
And I'm so happy it doesn't use the SPI library, I think it will work with the VirtualWire.h library for 433MHz radio transmission (www.airspayce.com/mikem/arduino/VirtualWire/)

I  have a newbie question.... I well see how you define the begin, contrast, write, etc.. functions, but I do not see anything about the print. How does it work ?

Thanks

**Comment by carlosefr** [comment]
The `PCD8544` class overrides the `write()` method from its base class (`Print`). The base class provides the `print()` method, which may do its own buffering and other things and calls `write()` to do the actual output.

**Comment by philippedc** [comment]
ok thank you !
